### PR TITLE
Add burner binary sensor

### PR DESCRIPTION
**Pull request by boltgolt**
This implements #13 as `binary_sensor.burner_status`.

### CODE REVIEW

**Comment by costastf** [comment]
Hi @Boltgolt, Thanks for this! Wouldn't you think that it would be better to expose a toon.burner_on that would return a boolean in toonlib to implement this feature, instead of reaching into the thermostat state for this? If you do I would be happy to implement it in toonlib and you can refactor this. If not, I can just merge this. Let me know!

**Comment by boltgolt** [comment]
That's a great idea, burner_on would be so much clearer for anyone using the library. I originally had no idea what this property did and had to manually test it by turning on the burner. 

I'll push a version using toon.burner_on later today.

**Comment by costastf** [comment]
Version 1.1.0 of toonlib (with the timeout problem) exposes a burner_on boolean property on toon object. Please also update the dependency to match on your update.

**Comment by costastf** [comment]
Thanks!

**Pull request merged**
