### PR TITLE
Added icons to sensors and a small readme update

### PR DESCRIPTION
**Pull request by boltgolt**
The icons of the toon sensors were the default `mdi:eye`, instead of something more representable. Added what i thought were the most fitting icons but do change them if you find something better.

### CODE REVIEW

**Review by costastf — APPROVED** [review]
Lovely, thanks!

**Comment by boltgolt** [comment]
@costastf what's stopping this component from being included in the next home assistant release, still [the presets](https://github.com/home-assistant/home-assistant/pull/7527)?

**Comment by costastf** [comment]
Yes, i think so. I made some changes using built in  states but we 
didn't really try to merge them since we were a bit bumped out by the 
way the first MR was treated.

kind regards

Costas

**Comment by boltgolt** [comment]
I can imagine, would be great to have toon in home assistant by default and in the components list though

**Comment by costastf** [comment]
Sure, we (@krokat and I) agree, If you want to take a stub at it please 
go ahead. It might even be accepted as it is with my latest changes.


kind regards

Costas

**Pull request merged**
